version: "3.9"
services:
  broker:
    image: eclipse-mosquitto
    container_name: mqtt_broker
    ports:
      - "1883:1883"  # MQTT Port
      - "9001:9001"  # WebSocket Port (optional)
    # network_mode: "host"
    volumes:
      - ./mqtt-broker/mosquitto.conf:/mosquitto/config/mosquitto.conf  # Custom config
      - ./mqtt-broker/data:/mosquitto/data  # Persistence storage
      - ./mqtt-broker/log:/mosquitto/log  # Log storage

  sensor:
    build:
      context: ./sensor
    network_mode: "host"
    image: python-sensor-service
    container_name: sensor_container
    depends_on:
      - broker
